# see : https://docs.github.com/fr/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll
# remote_theme: pages-themes/leap-day@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Villa des Luquettes
description: Villa familiale avec piscine dans la belle campagne provençale de la Cadière-d’Azur idéale pour 2 familles (220m2, 7 chambres, 14 couchages) 1542F Chemin des Luquettes, La Cadière-d’Azur


lsi: false
safe: true
source: https://github.com/gmoulard/vdlwebsite
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  extensions:
    - autolink
    - footnotes
    - smart
url: https://villadesluquettes.com/
name: Villa des Luquettes
