# Site settings
title: Your Title Here
description: > # this means to ignore newlines until "baseurl:"
repository: vvalchev/creative-theme-jekyll-new
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https:/villadesluquettes.com" # the base hostname & protocol for your site
author: Guillaume et Valerie
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
