# see : https://docs.github.com/fr/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll
lsi: false
safe: true
source: https://github.com/gmoulard/vdlwebsite
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  extensions:
    - autolink
    - footnotes
    - smart
url: https://villadesluquettes.com/
name: Villa des Luquettes
